### ISSUE TITLE
Does not work with XCode 10.0

### ISSUE THREAD

**Issue by akshitzaveri** [rjoudrey/swift-init-generator#4]
I followed installation instructions as below and nothing happened.

> Clone or download the source code
> Configure the code signing on both targets
> Run the target Swift Initializer Generator
> Restart Xcode

**Comment by crabman448** [comment]
Same :(

**Comment by markvasiv** [comment]
I was able to set it up in Xcode 10 the following way:
1. Archive the target, export it and move to Applications folder
2. Close XCode
3. Run the app from the Applications folder
4. Go to Settings -> Extensions and select a checkbox under "Swift Initialiser Generator"

**Comment by rjoudrey** [comment]
I updated the instructions in the readme
